### ISSUE TITLE
Update and add missing parts of the DSL definition

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#396]
**Priorities**
- [x] adjustments to optionals after thesis writing https://github.com/benchflow/benchflow/issues/401 (fixed in PR https://github.com/benchflow/benchflow/pull/439)
- [x] enable/disable stored knowledge https://github.com/benchflow/benchflow/issues/444 (fixed in PR https://github.com/benchflow/benchflow/pull/443)
- [x] check how description is serialized, now got `Some(ParallelMultiple11Activiti5210TestMultipleExploreUsers)` in demo mode (fixed in https://github.com/benchflow/benchflow/pull/455)
- [x] description is null if not specified https://github.com/benchflow/benchflow/issues/419 (fixed in https://github.com/benchflow/benchflow/pull/455)
- [x]  remove the `jitpack.io` repository (if not needed) https://github.com/benchflow/benchflow/issues/424#issuecomment-309496973 (fixed in https://github.com/benchflow/benchflow/pull/456)
- [x] rename API objects to include API in the name https://github.com/benchflow/benchflow/issues/388 (fixed in https://github.com/benchflow/benchflow/pull/457)
- [x] typo in demo converter test https://github.com/benchflow/benchflow/issues/406 (fixed in https://github.com/benchflow/benchflow/pull/458)
- [x] experiment termination criteria (type missing - double check with DSL definition) (fixed in https://github.com/benchflow/benchflow/pull/459)
- [x] change `configuration.termination_criteria.experiment.number` to `configuration.termination_criteria.experiment.number_of_trials` (fixed in https://github.com/benchflow/benchflow/pull/460)
- [x] (check) validation strategies https://github.com/benchflow/benchflow/issues/338. => Available but only `random-validation-set` is enabled since it is the first to be supported.
- [x]  adjust goal types https://github.com/benchflow/benchflow/issues/461 (fixed in https://github.com/benchflow/benchflow/pull/462)

**Next Tasks**
- [x] enable `enumerations` use in Java https://github.com/benchflow/benchflow/issues/447 (fixed in https://github.com/benchflow/benchflow/pull/463)
- [x] step function  https://github.com/benchflow/benchflow/issues/397 (fixed in https://github.com/benchflow/benchflow/pull/465)
- [x] convert exploration space to Java compatible https://github.com/benchflow/benchflow/issues/391 (needs discussion)
- [ ] change single and multiple collector types into one type with a list of values
- [ ] assert environment variables are only strings https://github.com/benchflow/benchflow/issues/407
- [ ] initial semantic checks https://github.com/benchflow/benchflow/issues/400 (partially fixed in PR https://github.com/benchflow/benchflow/pull/551)
- [ ] define and add observations and possible configurations https://github.com/benchflow/benchflow/issues/343 (needs discussion)
- [ ] workload model - inter operations timings are not properly defined since the distribution specification is missing 
- [ ] docker compose v3 for specifying resources https://github.com/benchflow/benchflow/issues/380
- [ ] add support for http workloads https://github.com/benchflow/benchflow/issues/375
- [ ] Max90th response time for WfMS https://github.com/benchflow/benchflow/issues/122
- [ ] default data collection (faban) values https://github.com/benchflow/benchflow/issues/437
- [ ] improve `DemoConverterTest` https://github.com/benchflow/benchflow/issues/438
- [ ] semantic check for `users` in experiment https://github.com/benchflow/benchflow/issues/441
 
**Later**
- [ ] (check) add confidence interval termination criteria https://github.com/benchflow/benchflow/issues/344
- [ ] BenchFlow internal settings https://github.com/benchflow/benchflow/issues/321
- [ ] SUT configuration https://github.com/benchflow/benchflow/issues/398

**Comment by VincenzoFerme** [comment]
@jeppe-style: Related to the following Slack thread: https://benchflow.slack.com/archives/C5D75QHBN/p1495465359227559

**Comment by VincenzoFerme** [comment]
@jeppe-style: also consider https://benchflow.slack.com/conversation/C5D75QHBN/p1495488580740915

**Comment by jeppe-style** [comment]
That is considered with https://github.com/benchflow/benchflow/issues/375 (also linked above)
