### ISSUE TITLE
Questions on the Test Manager after Code Review

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#425]
Related to https://github.com/benchflow/benchflow/issues/244. Some of the following applies also to other services.

- [ ] 1. Why do you ignore `BenchFlowTestManagerApplicationDemo.java` in https://github.com/benchflow/benchflow/blob/devel/benchflow-test-manager/.gitignore#L5
- [ ] 2. Versions to move in the properties setting of the `pom.xml`: https://github.com/benchflow/benchflow/blob/devel/benchflow-test-manager/pom.xml#L245
- [ ] 3. Remove the `api` subproject: https://github.com/benchflow/benchflow/tree/devel/benchflow-test-manager/api (see https://github.com/benchflow/benchflow/issues/227#issuecomment-299193469)
- [ ] 4. Remove the `raml` folder: https://github.com/benchflow/benchflow/tree/devel/benchflow-test-manager/application/raml
- [ ] 5. Better organise the artefacts in the `test/resource` folder so that it is straightforward to get for what they are used. A good example is what you started to do with the `exploration` folder: https://github.com/benchflow/benchflow/tree/devel/benchflow-test-manager/application/src/test/resources. For example it is not clear what the following folder is meant to: https://github.com/benchflow/benchflow/tree/devel/benchflow-test-manager/application/src/test/resources/data/ParallelMultiple11, other than many other.
- [ ] 6. Define/Find a standard way to name the test classes (similar to the use of `IT` in the name for the Integration Tests), so that we can easily identify the different kind of tests we implement (unit, functional, ...)
- [ ] 7. Implement https://github.com/benchflow/benchflow/issues/108 and get rid of: https://github.com/benchflow/benchflow/tree/devel/benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/constants
- [ ] 8. Where is the `end` time of the experiment/test? It is fine to keep last modified, and at the end that is also reflected in `end`, or do you think it is not needed?: https://github.com/benchflow/benchflow/tree/devel/benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/models
- [ ] 9. Clearly identify the APIs that are meant for BenchFlow users, and the one used among the BenchFlow services. A comment should be enough: https://github.com/benchflow/benchflow/tree/devel/benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/resources
- [ ] 10. Why the `DAOs` are in the `services` folder?: https://github.com/benchflow/benchflow/tree/devel/benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/services/internal/dao
- [ ] 11. Reduce as much as possible the points in the services we need to touch when we want to extend the system with new supported DSL feature (related to: https://github.com/benchflow/benchflow/issues/391). For example now we also have redundancy information on this in the`DAOs`: https://github.com/benchflow/benchflow/blob/devel/benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/services/internal/dao/ExplorationModelDAO.java#L130
- [ ] 12. Refactor the `TestTaskScheduler` in different classes, because it is too big
- [ ] 13. Document why we have ` // running queue (1 element)` in `TestTaskScheduler` with a comment
- [ ] 14. Work on the TODO, or convert them to issue that has to be tracked in the code
- [ ] 15. Bump dependencies to the latest supported version
- [ ] 16. Fix codacy (check carefully the reported issues on the codacy dashboard by searching for the `test-manager` project in https://www.codacy.com/app/BenchFlow/benchflow/files?#), but alo check style and PMD code style issues
- [ ] 17. Why do you have tests in `BenchFlowTestManagerApplicationIT`?
- [ ] 18. Use the correct [logging level](https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm)

**Comment by VincenzoFerme** [comment]
The following warning appearing during the build should be solved:

```
SLF4J: The requested version 1.7.16 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.

===========


WARN  [2017-06-30 22:41:29,869] org.mongodb.morphia.mapping.MappedField: Parameterized types are treated as untyped Objects. See field 'users' on class cloud.benchflow.dsl.explorationspace.ExplorationSpaceGenerator$ExplorationSpaceDimensions
WARN  [2017-06-30 22:41:29,871] org.mongodb.morphia.mapping.MappedField: Parameterized types are treated as untyped Objects. See field 'usersDimension' on class cloud.benchflow.dsl.explorationspace.ExplorationSpaceGenerator$ExplorationSpace
WARN  [2017-06-30 22:41:29,943] org.mongodb.morphia.mapping.MappedField: Parameterized types are treated as untyped Objects. See field 'users' on class cloud.benchflow.dsl.explorationspace.ExplorationSpaceGenerator$ExplorationSpaceDimensions
WARN  [2017-06-30 22:41:29,944] org.mongodb.morphia.mapping.MappedField: Parameterized types are treated as untyped Objects. See field 'usersDimension' on class cloud.benchflow.dsl.explorationspace.ExplorationSpaceGenerator$ExplorationSpace
WARN  [2017-06-30 22:41:29,948] org.mongodb.morphia.mapping.MappedField: Parameterized types are treated as untyped Objects. See field 'users' on class cloud.benchflow.dsl.explorationspace.ExplorationSpaceGenerator$ExplorationSpaceDimensions
WARN  [2017-06-30 22:41:29,949] org.mongodb.morphia.mapping.MappedField: Parameterized types are treated as untyped Objects. See field 'usersDimension' on class cloud.benchflow.dsl.explorationspace.ExplorationSpaceGenerator$ExplorationSpace
WARN  [2017-06-30 22:41:29,953] org.mongodb.morphia.mapping.MappedField: Parameterized types are treated as untyped Objects. See field 'users' on class cloud.benchflow.dsl.explorationspace.ExplorationSpaceGenerator$ExplorationSpaceDimensions
WARN  [2017-06-30 22:41:29,954] org.mongodb.morphia.mapping.MappedField: Parameterized types are treated as untyped Objects. See field 'usersDimension' on class cloud.benchflow.dsl.explorationspace.ExplorationSpaceGenerator$ExplorationSpace


=============


[WARN] /pipeline/source/benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/BenchFlowTestManagerApplication.java:114: Distance between variable 'taskExecutor' declaration and its first usage is 7, but allowed 3.  Consider to make that variable as final if you still need to store its value in advance (before method calls that might do side effect on original value). [VariableDeclarationUsageDistance]
```

**Comment by jeppe-style** [comment]
8\. _"Where is the end time of the experiment/test? It is fine to keep last modified, and at the end that is also reflected in end, or do you think it is not needed?:"_
-> Until now I have only used last modified to note the end of the test/experiment/trial. I think it should be sufficient since once it is terminated the model should only be read and not updated.

10\. _"Why the DAOs are in the services folder?:"_
-> I put them as internal services since they are the interface to interact with the DB, in the same ways as the clients are the interfaces to interact with the external services.

17\. _"Why do you have tests in BenchFlowTestManagerApplicationIT"_
-> These are tests that interact with the complete application from the client's point of view. I put them into one class so that it is easy to see which interactions are possible and what the request and response looks like.

**Comment by VincenzoFerme** [comment]
We should introduce some guidelines so that when a `Strategy` is required to implement a functionality of the DSL, then there must be a standard way to define the names of these strategies so that we can have a dynamic load of the same without the need of changing core code.
