### ISSUE TITLE
First Release Burn Down Main Issues

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#467]
Summary of the most relevant features/improvements. Complete list: https://github.com/benchflow/benchflow/milestone/7

## System Functionality

- [ ] [Support More Workflow Management Systems (WfMSs)] (https://github.com/benchflow/benchflow/issues/452) (+ https://github.com/benchflow/benchflow/issues/123) **[BENCHFLOW, PhD, Internships / Other Users]**
- [ ] Support complete and ["smart" (basic `mars`)](https://github.com/benchflow/benchflow/issues/448) [exploration of configuration spaces](https://github.com/benchflow/benchflow/issues/408) with [different strategies to order the experiment execution](https://github.com/benchflow/benchflow/issues/287), [validation strategies](https://github.com/benchflow/benchflow/issues/338) and [termination criteria](https://github.com/benchflow/benchflow/issues/281) (+ https://github.com/benchflow/benchflow/issues/337, https://github.com/benchflow/benchflow/issues/338)  **[PhD]**
- [ ] [Support initial techniques to reuse stored knowledge](https://github.com/benchflow/benchflow/issues/381)  **[PhD]**
- [ ] [Improve Data Analysis part for flexibility](https://github.com/benchflow/benchflow/issues/453) (+ https://github.com/benchflow/benchflow/issues/60) **[Internships / Other Users]**
- [ ] [Improve Monitors and Collectors in terms of how fast is to extend them](https://github.com/benchflow/benchflow/issues/454) (+ https://github.com/benchflow/benchflow/issues/450) **[Internships / Other Users]**
- [ ] BenchFlow Test, Docker Compose and Test Bundle syntactic (+) and semantics validation (https://github.com/benchflow/benchflow/issues/432, https://github.com/benchflow/benchflow/issues/400, https://github.com/benchflow/benchflow/issues/48) **[Internships / Other Users]**
- [ ] [Make computed metrics more accessible](https://github.com/benchflow/benchflow/issues/101) **[Internships / Other Users]**
- [ ] [Clean REST APIs Definition](https://github.com/benchflow/benchflow/issues/102) **[Internships / Other Users]**
- [ ] [Faban LifeCycle](https://github.com/benchflow/benchflow/issues/553) **[PhD]**

## System Stability

- [ ] [Update Faban from upstream](https://github.com/benchflow/benchflow/issues/451) **[ALL]**
- [ ] [Handle most common unexpected runtime error during execution of tests on Faban](https://github.com/benchflow/benchflow/issues/285) **[BENCHFLOW, PhD]**
- [ ] [Improve the Way the Driver Check that a SUT is Ready](https://github.com/benchflow/benchflow/issues/162) **[BENCHFLOW, PhD]**
- [ ] [Undeploy from Faban after experiment is complete](https://github.com/benchflow/benchflow/issues/464) (+ https://github.com/benchflow/benchflow/issues/156) **[BENCHFLOW, PhD]**

## For Internship(s) / Collaborations

- [ ] [Finalise the support for http workloads](https://github.com/benchflow/benchflow/issues/375) **[Internships / Other Users]**
- [ ] [Enable Runs with Varying Loads ](https://github.com/benchflow/benchflow/issues/179) **[Internships / Other Users]**
- [ ] [Update the client to the new APIs](https://github.com/benchflow/benchflow/issues/324) **[Internships / Other Users]**
- [ ] [Add an APIs to register hosts](https://github.com/benchflow/benchflow/issues/314) (+ https://github.com/benchflow/benchflow/issues/306) and improve the [stability of the deployment manager](https://github.com/benchflow/benchflow/issues/61) **[Internships / Other Users]**
- [ ] [Redact the Initial Version of the Documentation](https://github.com/benchflow/benchflow/issues/51) **[Internships / Other Users]**
- [ ] [DevOps activities](https://github.com/benchflow/benchflow/issues/59), including define [an easier way to deploy the system](https://github.com/benchflow/benchflow/issues/119) **[Internships / Other Users]**

## For Papers

- [ ] Make a release **[Internships / Other Users]**
- [ ] Extend (with Guillaume) for Multi-tenancy Objective **[PhD]**
- [ ] Work on Knowledge Reuse **[PhD]**

-------------

## Jesper (@jeppe-style) 
Complete list: https://github.com/benchflow/benchflow/issues?q=is%3Aopen+assignee%3Ajeppe-style

- [ ] https://github.com/benchflow/benchflow/issues/403
- [ ] https://github.com/benchflow/benchflow/issues/37
- [ ] https://github.com/benchflow/benchflow/issues/332
- [ ] Document Mapping of Faban Statuses https://github.com/benchflow/benchflow/issues/488
- [ ] Document Test Decisions - https://github.com/benchflow/benchflow/issues/27
- [ ] Document implementation decisions - https://github.com/benchflow/benchflow/issues/327
- [ ] Document the code - https://github.com/benchflow/benchflow/issues/382
- [ ] Document the Idea on the way this is supposed to be done https://github.com/benchflow/benchflow/issues/44
- [ ] Document the code https://github.com/benchflow/benchflow/issues/57
- [ ] Cleanup code https://github.com/benchflow/benchflow/issues/103
- [ ] DSL leftover - https://github.com/benchflow/benchflow/issues/396
- [ ] Default DSL Values https://github.com/benchflow/benchflow/issues/105
- [ ] Constant values in the DSL https://github.com/benchflow/benchflow/issues/110
- [ ] Proper HATEOS on the APIs https://github.com/benchflow/benchflow/issues/128
- [ ] Minio Client Library https://github.com/benchflow/benchflow/issues/218, https://github.com/benchflow/benchflow/issues/268
- [ ] Pausing a Test https://github.com/benchflow/benchflow/issues/364
- [ ] What to do for Concurrency Handling https://github.com/benchflow/benchflow/issues/239
- [ ] Termination Criteria actually implemented and the ones that are future work https://github.com/benchflow/benchflow/issues/281
- [ ] https://github.com/benchflow/benchflow/issues/373
- [ ] https://github.com/benchflow/benchflow/issues/377
- [ ] Improve REST APIs Responses https://github.com/benchflow/benchflow/issues/494
- [ ] Handling of errors during tests
- [ ] Supported Base Objectives and Objectives
- [ ] Default Values: https://github.com/benchflow/benchflow/issues/437, https://github.com/benchflow/benchflow/issues/441
- [ ] Terminate Test: https://github.com/benchflow/benchflow/issues/485
- [ ] Undeploy from Faban - https://github.com/benchflow/benchflow/issues/464
- [ ] Bugs: https://github.com/benchflow/benchflow/issues/407, https://github.com/benchflow/benchflow/issues/477
- [ ] Code Reviews the hinder the correctness of the system: https://github.com/benchflow/benchflow/issues/425, https://github.com/benchflow/benchflow/issues/426, https://github.com/benchflow/benchflow/issues/427
